### ISSUE TITLE
pyllamacpp issue

### ISSUE THREAD

**Issue by Meirzhan05** [nomic-ai/pygpt4all#101]
I do not understand why I am getting this issue. I think I have done everything right. I have Windows 10.
Issue:
Traceback (most recent call last):
  File "c:\Users\Hp\Desktop\py\ai.py", line 1, in <module>
    from pygpt4all import GPT4All
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygpt4all\__init__.py", line 1, in <module>
    from pygpt4all.models.gpt4all import GPT4All
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygpt4all\models\gpt4all.py", line 13, in <module>
    import pyllamacpp.model
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyllamacpp\model.py", line 20, in <module>
    import _pyllamacpp as pp
ImportError: DLL load failed while importing _pyllamacpp: A dynamic link library (DLL) initialization routine failed.

Did you have this issue? How did you solve it?

**Comment by abdeladim-s** [comment]
@Meirzhan05,

It is a duplicate of #53, please take a look at this [comment](https://github.com/nomic-ai/pygpt4all/issues/53#issuecomment-1529772010).
