### ISSUE TITLE
Error running example code

### ISSUE THREAD

**Issue by GrahamboJangles** [nomic-ai/pygpt4all#55]
```
Exception has occurred: ModuleNotFoundError
No module named 'pyllamacpp.model'; 'pyllamacpp' is not a package
```

Yes, I have pyllamacpp installed through pip.

**Comment by abdeladim-s** [comment]
hi @GrahamboJangles,

Could you please give more clarifications! 
If the package is installed properly, then it should be imported like any pip package!

**Comment by GrahamboJangles** [comment]
> hi @GrahamboJangles,
> 
> Could you please give more clarifications! If the package is installed properly, then it should be imported like any pip package!

Thank you for your quick reply. I figured it should be that simple, but for some reason it's not. I even tried a venv virtual environment. 
```
Microsoft Windows [Version 10.0.19044.2728]
(c) Microsoft Corporation. All rights reserved.

G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>activate.bat

G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>.\env\Scripts\activate

(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>pip install pyllamacpp
Collecting pyllamacpp
  Using cached pyllamacpp-1.0.6-cp310-cp310-win_amd64.whl (191 kB)
Collecting streamlit
  Using cached streamlit-1.21.0-py2.py3-none-any.whl (9.7 MB)
Collecting sentencepiece
  Downloading sentencepiece-0.1.98-cp310-cp310-win_amd64.whl (977 kB)
     ---------------------------------------- 977.8/977.8 KB 7.7 MB/s eta 0:00:00
Collecting torch
  Downloading torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
     ---------------------------------------- 172.3/172.3 MB 1.9 MB/s eta 0:00:00
Collecting streamlit-ace
  Using cached streamlit_ace-0.1.1-py3-none-any.whl (3.6 MB)
Collecting protobuf<4,>=3.12
  Downloading protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
     ---------------------------------------- 904.0/904.0 KB 11.5 MB/s eta 0:00:00
Collecting pillow>=6.2.0
  Downloading Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 15.9 MB/s eta 0:00:00
Collecting validators>=0.2
  Using cached validators-0.20.0-py3-none-any.whl
Collecting numpy
  Downloading numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
     ---------------------------------------- 14.8/14.8 MB 10.9 MB/s eta 0:00:00
Collecting rich>=10.11.0
  Downloading rich-13.3.4-py3-none-any.whl (238 kB)
     ---------------------------------------- 238.7/238.7 KB 14.3 MB/s eta 0:00:00
Collecting requests>=2.4
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.8/62.8 KB 3.3 MB/s eta 0:00:00
Collecting cachetools>=4.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting pandas<2,>=0.25
  Downloading pandas-1.5.3-cp310-cp310-win_amd64.whl (10.4 MB)
     ---------------------------------------- 10.4/10.4 MB 18.2 MB/s eta 0:00:00
Collecting tzlocal>=1.1
  Downloading tzlocal-4.3-py3-none-any.whl (20 kB)
Collecting blinker>=1.0.0
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting packaging>=14.1
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ---------------------------------------- 48.9/48.9 KB ? eta 0:00:00
Collecting typing-extensions>=3.10.0.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ---------------------------------------- 96.6/96.6 KB ? eta 0:00:00
Collecting altair<5,>=3.2.0
  Using cached altair-4.2.2-py3-none-any.whl (813 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ---------------------------------------- 247.7/247.7 KB 15.8 MB/s eta 0:00:00
Collecting pydeck>=0.1.dev5
  Using cached pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
Collecting watchdog
  Using cached watchdog-3.0.0-py3-none-win_amd64.whl (82 kB)
Collecting pympler>=0.9
  Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ---------------------------------------- 184.3/184.3 KB 11.6 MB/s eta 0:00:00
Collecting pyarrow>=4.0
  Using cached pyarrow-11.0.0-cp310-cp310-win_amd64.whl (20.6 MB)
Collecting importlib-metadata>=1.4
  Downloading importlib_metadata-6.3.0-py3-none-any.whl (22 kB)
Collecting tornado>=6.0.3
  Using cached tornado-6.2-cp37-abi3-win_amd64.whl (425 kB)
Collecting filelock
  Downloading filelock-3.11.0-py3-none-any.whl (10.0 kB)
Collecting sympy
  Downloading sympy-1.11.1-py3-none-any.whl (6.5 MB)
     ---------------------------------------- 6.5/6.5 MB 16.6 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 18.9 MB/s eta 0:00:00
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.1/133.1 KB 8.2 MB/s eta 0:00:00
Collecting jsonschema>=3.0
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting toolz
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.7/62.7 KB ? eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ---------------------------------------- 502.3/502.3 KB 15.9 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
     ---------------------------------------- 97.1/97.1 KB 5.8 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
     ---------------------------------------- 140.9/140.9 KB 8.7 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.5/61.5 KB 3.4 MB/s eta 0:00:00
Collecting pygments<3.0.0,>=2.13.0
  Downloading Pygments-2.15.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 18.3 MB/s eta 0:00:00
Collecting markdown-it-py<3.0.0,>=2.2.0
  Using cached markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ---------------------------------------- 341.8/341.8 KB 20.7 MB/s eta 0:00:00
Collecting decorator>=3.4.0
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting mpmath>=0.19
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ---------------------------------------- 536.2/536.2 KB 17.0 MB/s eta 0:00:00
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting attrs>=17.4.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ---------------------------------------- 60.0/60.0 KB ? eta 0:00:00
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-cp310-cp310-win_amd64.whl (62 kB)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: sentencepiece, pytz, mpmath, zipp, watchdog, urllib3, tzdata, typing-extensions, tornado, toolz, toml, sympy, smmap, six, pyrsistent, pympler, pygments, protobuf, pillow, packaging, numpy, networkx, mdurl, MarkupSafe, idna, filelock, entrypoints, decorator, colorama, charset-normalizer, certifi, cachetools, blinker, attrs, validators, requests, pytz-deprecation-shim, python-dateutil, pyarrow, markdown-it-py, jsonschema, jinja2, importlib-metadata, gitdb, click, tzlocal, torch, rich, pydeck, pandas, gitpython, altair, streamlit, streamlit-ace, pyllamacpp
Successfully installed MarkupSafe-2.1.2 altair-4.2.2 attrs-22.2.0 blinker-1.6.2 cachetools-5.3.0 certifi-2022.12.7 charset-normalizer-3.1.0 click-8.1.3 colorama-0.4.6 decorator-5.1.1 entrypoints-0.4 filelock-3.11.0 gitdb-4.0.10 gitpython-3.1.31 idna-3.4 importlib-metadata-6.3.0 jinja2-3.1.2 jsonschema-4.17.3 markdown-it-py-2.2.0 mdurl-0.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.24.2 packaging-23.1 pandas-1.5.3 pillow-9.5.0 protobuf-3.20.3 pyarrow-11.0.0 pydeck-0.8.0 pygments-2.15.0 pyllamacpp-1.0.6 pympler-1.0.1 pyrsistent-0.19.3 python-dateutil-2.8.2 pytz-2023.3 pytz-deprecation-shim-0.1.0.post0 requests-2.28.2 rich-13.3.4 sentencepiece-0.1.98 six-1.16.0 smmap-5.0.0 streamlit-1.21.0 streamlit-ace-0.1.1 sympy-1.11.1 toml-0.10.2 toolz-0.12.0 torch-2.0.0 tornado-6.2 typing-extensions-4.5.0 tzdata-2023.3 tzlocal-4.3 urllib3-1.26.15 validators-0.20.0 watchdog-3.0.0 zipp-3.15.0
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\Scripts\python.exe -m pip install --upgrade pip' command.

(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>
(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>
(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>python "pyllamacpp 2.py"
Traceback (most recent call last):
  File "G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\pyllamacpp 2.py", line 1, in <module>
    from pyllamacpp.model import Model
  File "G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\pyllamacpp.py", line 1, in <module>
    from huggingface_hub import hf_hub_download
ModuleNotFoundError: No module named 'huggingface_hub'

(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>pip install huggingface_hub
Collecting huggingface_hub
  Using cached huggingface_hub-0.13.4-py3-none-any.whl (200 kB)
Requirement already satisfied: filelock in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (3.11.0)
Collecting tqdm>=4.42.1
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ---------------------------------------- 77.1/77.1 KB 2.2 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.9 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (23.1)
Requirement already satisfied: requests in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (2.28.2)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
     ---------------------------------------- 151.7/151.7 KB 4.6 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (4.5.0)
Requirement already satisfied: colorama in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (3.1.0)
Installing collected packages: tqdm, pyyaml, huggingface_hub
Successfully installed huggingface_hub-0.13.4 pyyaml-6.0 tqdm-4.65.0
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\Scripts\python.exe -m pip install --upgrade pip' command.

(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>pip install huggingface_hub
Requirement already satisfied: huggingface_hub in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (0.13.4)
Requirement already satisfied: tqdm>=4.42.1 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (4.65.0)
Requirement already satisfied: filelock in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (3.11.0)
Requirement already satisfied: requests in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (2.28.2)
Requirement already satisfied: pyyaml>=5.1 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (4.5.0)
Requirement already satisfied: packaging>=20.9 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from huggingface_hub) (23.1)
Requirement already satisfied: colorama in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
Requirement already satisfied: idna<4,>=2.5 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (3.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in g:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\lib\site-packages (from requests->huggingface_hub) (2022.12.7)
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\env\Scripts\python.exe -m pip install --upgrade pip' command.

(env) G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64>python "pyllamacpp 2.py"
Traceback (most recent call last):
  File "G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\pyllamacpp 2.py", line 1, in <module>
    from pyllamacpp.model import Model
  File "G:\llama\alpaca-bin-models\alpaca-win\llama-master-3e6e70d-bin-win-avx2-x64\pyllamacpp.py", line 2, in <module>
    from pyllamacpp.model import Model
ModuleNotFoundError: No module named 'pyllamacpp.model'; 'pyllamacpp' is not a package
```

**Comment by abdeladim-s** [comment]
@GrahamboJangles the filename you are using to write the script is the same as the package. 
Please modify the filename from `pyllamacpp.py` to a different name ?

**Comment by GrahamboJangles** [comment]
> @GrahamboJangles the filename you are using to write the script is the same as the package. Please modify the filename from `pyllamacpp.py` to a different name ?

Ah yes I thought of that too. You can see I ran "pyllamacpp 2.py" and I even tried "test.py" and still got the same error... Something must be wrong with my setup though I'm sure

**Comment by abdeladim-s** [comment]
@GrahamboJangles Yes that's probably is the issue.
