### ISSUE TITLE
ImportError: DLL load failed while importing _pyllamacpp: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by Burgeon0110** [nomic-ai/pygpt4all#75]
>>> from pygpt4all.models.gpt4all import GPT4All
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pygpt4all\pygpt4all\models\gpt4all.py", line 18, in <module>
    from pyllamacpp.model import Model
  File "E:\Python\Python311\Lib\site-packages\pyllamacpp\model.py", line 21, in <module>
    import _pyllamacpp as pp
ImportError: DLL load failed while importing _pyllamacpp: 动态链接库(DLL)初始化例程失败。

**Comment by abdeladim-s** [comment]
Duplicate of #53
